import { StyleSheet } from 'react-native';
import { ThemeColors } from '../../contexts/ThemeContext';

export const createStyles = (colors: ThemeColors) => StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  contentContainer: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 20 },
  label: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.text,
    marginBottom: 4,
  },
  required: {
    color: colors.danger,
    fontWeight: '600',
  },
  input: {
    borderWidth: 1,
    borderColor: colors.inputBorder,
    borderRadius: 8,
    padding: 10,
    marginBottom: 12,
    backgroundColor: colors.inputBackground,
    color: colors.text,
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    gap: 10,
  },
  list: { flex: 1, marginTop: 20 },
  item: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 10,
    marginBottom: 10,
    backgroundColor: colors.card,
  },
  title: { fontWeight: 'bold', fontSize: 16, color: colors.text },
  sectionTitle: {
    fontWeight: '600',
    fontSize: 15,
    marginTop: 16,
    marginBottom: 8,
    color: colors.text,
  },
  metaRow: { flexDirection: 'row', alignItems: 'center' },
  modalView: { flex: 1, padding: 16, backgroundColor: colors.background },
  imageContainer: {
    marginBottom: 10,
  },
  imageWrapper: {
    position: 'relative',
    marginRight: 10,
  },
  imagePreview: {
    width: 100,
    height: 100,
    borderRadius: 8,
  },
  deleteImageButton: {
    position: 'absolute',
    top: -5,
    right: -5,
    backgroundColor: colors.danger,
    borderRadius: 12,
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  deleteImageText: {
    color: 'white',
    fontSize: 14,
    fontWeight: 'bold',
  },
});